# Generated by Django 4.1.2 on 2022-10-28 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artiste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='musicapp.artiste'),
        ),
    ]
