# Generated by Django 4.1.2 on 2022-11-03 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_alter_artiste_age_alter_lyric_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='artiste',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicapp.artiste'),
            preserve_default=False,
        ),
    ]
